### PR TITLE
Update project structure and README

### PR DESCRIPTION
**Pull request by blesuer0729**
Going forward it will be easier to add, remove, and make updates to JSlim with a basic project structure. Putting the entire code logic in index.js is generally something you would want to avoid.

Made updates to the README based on Markdown rules and updating the contributing section based on how to add new files to the project under the proposed strcuture.

### CODE REVIEW

**Comment by oliverisMisiunas** [comment]
Wow! Insane! This is a huge contribution! Thank you very very much! It seems that I will have to change the tutorial on the website a bit. Will get to that immediately after merging your PR. 
Again, thank you very much! Best of luck to you!

**Comment by oliverisMisiunas** [comment]
Oh, forgot to mention. I will be making a page on the website to mention every contributor. How would you like me to mention you? By name? Please let me know if you want me to link your GitHub profile. You can give me links to your social media that you would like me to link.

**Comment by blesuer0729** [comment]
@oliverisMisiunas You can use my name and github :) I don't have social media but I am glad to keep contributing.

**Comment by oliverisMisiunas** [comment]
Hey! It seems that the library stopped working after changing the structure. I'm getting this error when opening the index.html file:
```
Access to script at 'file:///C:/Users/mycomputer/Desktop/dsa/node_modules/jslim-library/src/index.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

However, the error changes to this one when I am opening the same file with Live Server:
```
GET http://127.0.0.1:5500/node_modules/jslim-library/src/plugin/JSlim net::ERR_ABORTED 404 (Not Found)
```

Do you know what could be causing this? Is this problem also present on your computer?

**Pull request merged**
